- src/modules/ResultDataProvider.ts
> #117 Add logs for debugging testing by case level

- src/modules/ResultDataProvider.ts
- Changed URL
- Removed temporary logs
> #126 Appendix A+B errors

- src/modules/TestDataProvider.ts
- src/utils/logger.ts
- Adding checks if test cases were found
- Added relevant logs
- Changed logger settings
> #135 Error while generating STR with no test cases found

- src/helpers/tfs.ts
- src/modules/ResultDataProvider.ts
- src/modules/TestDataProvider.ts
- Add more logs
- Changed URLS to support TFS API
- Add errors if there is either project nor plan selected
> #136 Unable to create some requests with specific suites - Log tracing

- src/helpers/tfs.ts
- src/modules/ResultDataProvider.ts
- Added throw error when cannot fetch data from TFS
- Added async functionality where is needed
- Added additional checks and error catching
> #136 Unable to create some requests with specific suites

- package-lock.json
- src/helpers/tfs.ts
- src/models/tfs-data.ts
- src/modules/ResultDataProvider.ts
- Fixing steps numeration by array index
- map step id to the corresponding step index
- replace request usage with axios
> #143 Inconsistent step index between balmas and cloud

- src/modules/TestDataProvider.ts
- src/modules/TicketsDataProvider.ts
- tsconfig.json
- Add support for fetching query data (only for linked test and requirments)
> #146 Support for WIQL fetch data

- src/modules/ResultDataProvider.ts
- Add test case id to the key with the combination of the test run ID and Test Result ID
- Handle test case which was not had any runs
> #156 Alignment with test case steps are incorrect

- src/modules/TicketsDataProvider.ts
- Bug fix: Incorrect customer id field
- Make the table more dynamic depending on the queries and if there is any value in the table
> #162 Changes To Query fetching

- src/models/tfs-data.ts
- src/modules/ResultDataProvider.ts
- src/modules/TestDataProvider.ts
- src/utils/testStepParserHelper.ts
- Parsing Compref (shared steps) for both STR and STD
> #163 Fix Shared Steps

- src/modules/JfrogDataProvider.ts
- Changed the try clause position
> #184 Error while fetching Jfrog data

- src/index.ts
- src/modules/PipelinesDataProvider.ts
- Added recent release artifact Info
> #185 Add Release components table

- src/models/tfs-data.ts
- src/modules/TicketsDataProvider.ts
- Added support for fetching query result data with description for SW overview
> #187 System overview query - display has paragraphs

- src/modules/GitDataProvider.ts
- Added a set of included workitems
> #197 Commit duplicates

- src/modules/PipelinesDataProvider.ts
- exlude failed or canceled build results
> #200 Exclude failed pipelines

- src/modules/TicketsDataProvider.ts
- add support for possible bugs query results
> #188 Possible known bugs section

- src/modules/TicketsDataProvider.ts
- Add support for covered requirements by getting test-requirement queries
- Supporting both STD and STR
> #205 Add options to filter linked requirement

- src/modules/GitDataProvider.ts
> #214 Fetching wrong repositories

- src/helpers/tfs.ts
- src/modules/GitDataProvider.ts
- add support for submodules parsing
> #208 Add support for submodules

- src/helpers/tfs.ts
- src/modules/TicketsDataProvider.ts
- Added timeout for tfs calls and retrys
- Added the ability to download files from azure devops and convert them to base64
> #211 Documents not opening

- src/modules/JfrogDataProvider.ts
- src/modules/ResultDataProvider.ts
- src/modules/TicketsDataProvider.ts
- Throwing the error object so it will be easier to find where is the issue
> #243 skins.forEach is Undefined

- src/modules/ResultDataProvider.ts
- Refacored the fetch linked wi process to use batching
> #257 Open PCR cannot grab more than 230 wi

- src/models/tfs-data.ts
- src/modules/ResultDataProvider.ts
- src/modules/TestDataProvider.ts
- Adding support for adding run result attachments into the step execution table
> #254 Add Step analysis attachments into the Step Execution table

- src/helpers/tfs.ts
- src/modules/GitDataProvider.ts
- Add support for getting git objects
- Increased Timeout of the API call to 3 seconds
- Changed Error catching in the TFS helper
> #228 Get workitems for svd via tags, branches, commits

- src/helpers/tfs.ts
- src/modules/GitDataProvider.ts
- Adjustments for the logs of not found files
- Support for specific file paths for service.json
> #270 Add support for handling services.json for SVD Release Range

- src/modules/ResultDataProvider.ts
- Remove detailed results table if hard copy is enabled
> #269 Remove Chapter 4.2 if hard copy enabled

- src/helpers/tfs.ts
- src/modules/TestDataProvider.ts
- Parallize the Test Case structuing
- Changed the API calls and connectivity to keep alive to optimize connections
> #152 Improve Performance for STD document generation

- src/helpers/tfs.ts
- src/modules/GitDataProvider.ts
- src/modules/MangementDataProvider.ts
- Getting User profile by token
- Sorting the repo list without case sensitive
- Major fix with SVD - there was a problem with fetching some requests in the tfs.ts
> #274 Favorites Dialog

- src/modules/ResultDataProvider.ts
- Add support for related bugs
> #282 Bug Support for Test Reporter

- src/models/tfs-data.ts
- src/modules/TestDataProvider.ts
> #292 Sub table to Open Mom - like in EASPP

- src/models/tfs-data.ts
- src/modules/GitDataProvider.ts
- src/modules/TicketsDataProvider.ts
> #287 Linked Wi & Filter by area path

- src/modules/ResultDataProvider.ts
- Fixed limitation of 'Tests' relations to any type
> #296 No support for all linked bugs or CR in STR

- src/modules/ResultDataProvider.ts
- add sorting to the test log values
> #299 Test Log - Sort By execution Date

- src/modules/ResultDataProvider.ts
- Add support for assignedTo, subSystem and relatedCRs
- Allow more Link types
> #301 New fields support for Test Reporter

- src/models/tfs-data.ts
- src/modules/ResultDataProvider.ts
- src/modules/TestDataProvider.ts
- src/modules/TicketsDataProvider.ts
- src/modules/test/ResultDataProvider.test.ts
- src/modules/test/testDataProvider.test.ts
- src/utils/DataProviderUtils.ts
- Add support for PCRs links
- Fetch data like trace analysis
> #297 Support for query in Open PCR

- src/modules/ResultDataProvider.ts
Reverts elisradevops/docgen-data-provider-package#80
> Revert "Bug fix"

- src/modules/ResultDataProvider.ts
Reverts elisradevops/docgen-data-provider-package#81
> Revert "Revert "Bug fix""

- src/models/tfs-data.ts
- src/modules/ResultDataProvider.ts
- Improved the fetching for Active test cases
> #328 Active test cases do not getting additional fields

- src/modules/GitDataProvider.ts
- Add unrelated changesets to SVD
- minor fix for linked relationship
> #329 Changeset without any linked WI should be included --- Appendix

- src/helpers/helper.ts
- src/modules/TestDataProvider.ts
- Fixed nested suite selection
> #341 Hide Suite name when there is only one suite in a plan

- src/modules/GitDataProvider.ts
- Add support for get if a tag or a branch exists
> #347 Support for branch to branch from services.json

- src/modules/GitDataProvider.ts
- Fetch data sorted by commit history
> #354 Sort object ref by commit history

- src/modules/TicketsDataProvider.ts
- Fetch relevant queries for SRS
> #422 Support SRS

- src/helpers/tfs.ts
- src/modules/GitDataProvider.ts
- src/modules/TicketsDataProvider.ts
- add support for fetching workitem types icons
- Add support for fetching workitem types and states
> #260309 SVD - Add more filtering options
